---
title: "STA257"
author: "Neil Montgomery | HTML is official | PDF versions good for in-class use only"
date: "Last edited: `r format(Sys.time(), '%Y-%m-%d %H:%M')`"
output: 
  ioslides_presentation: 
    css: '../styles.css' 
    widescreen: true 
    transition: 0.001
---
\newcommand\given[1][]{\:#1\vert\:}
\newcommand\P[1]{P{\left(#1\right)}}

## binomial to Poisson { .small }

From last time:

* Take an interval $(0,t)$ and an $np = \lambda t$;

* Split into subintervals;

* Stick a Bernoulli trial in each subinterval;

* In such a way that you'd expect about the same number $\lambda t$ of events to occur in $(0,t)$.

* Observe that only one event can happen in each subinterval and non-overlapping collections of subintervals are independent. 

Add for today:

* Rather than $(0,t)$ we could have taken any arbitrary $(s,t)$ (different $t$!). We'll expect about $\lambda(t-s)$ events to take place within $(s,t)$.

## pass to the limit { .build }

Define $\lambda(t-s)$ be fixed and always equal to $np$. This implies $p = \frac{\lambda(t-s)}{n}$.

What happens to $X_n\sim \text{Binomial}\left(n, \frac{\lambda (t-s)}{n}\right)$ distributions as $n \to \infty$? 

$$\lim_{n \to \infty} P(X_n = k) = \frac{[\lambda(t-s)]^k}{k!}e^{-\lambda(t-s)}$$

Note: $\lambda$ itself is the rate of occurrences per unit time. 

Let $Y\sim\text{Poisson}(\lambda(t-s))$. The above implies more:

$$\lim_{n \to \infty} P(X_n \in A) = P(Y \in A),$$
for $A \in \mathbb{R}$. So the "distributions" converge. 

## more on the limit result

This limit result serves a few purposes:

1. Because of the speed and accuracy of the convergence, one can approximate binomial probabilities. 

2. Motivate use of Poisson distribution as a suitable probability model (large $n$, small $p$, one-at-a-time events, etc.)

## binomial approximation example 

Suppose $X \sim \text{Binomial}(n, p)$ with $n=10000$ and $p=0.001$. 

Calculate and approximate $P(X \le k)$ for $k \in \{0,1,2,3,4,5\}$.

Calculation: $\sum_{i=0}^k {10000 \choose i} (0.001)^i(0.999)^{10000-i}$

Approximation: $\sum_{i=0}^k \frac{10^ie^{-10}}{i!}$, using $\lambda = np = 10$

```{r, echo=FALSE, results='asis'}
library(xtable)
k <- 0:5
b_p <- data.frame(rbind(dbinom(k, 10000, 0.001), dpois(k, 10), dbinom(k, 10000, 0.001) - dpois(k, 10)))
colnames(b_p) <- paste0("$k=", k, "$")
rownames(b_p) <- c("Binom", "Poisson", "Diff")
print(xtable(b_p, digits=-3), sanitize.text.function = function(x) {x}, type = "html", comment = FALSE, booktabs=TRUE)
```

## the "completely random" nature of the Bernoulli process { .build }

Only one "event" can happen at a time.

Non-overlapping sets of trials are independent.

Memoryless (as seen via Geometric distributions).

Another idea: suppose by the $n^{th}$ trial exactly 1 event has occurred. Let $Y$ be the index of the trial where the event occurred. This is a random variable. What is it's distribution?

Note: sometimes $Y$ is said to have a "discrete uniform distribution on $\{1,2,\ldots,n\}$"

## the Poisson process - I { .build .small }

Suppose as *time* unfolds, events occur, and we keep track of the number of events that occur over time. Denote by $N(t)$ the number of events that happen inside $(0,t]$.

(So $N(t) - N(s)$ is the number of events that happen in some $(s,t]$ with $s < t$).

Let's say we want the occurrence of events to be "completely random" in analogy to a Bernoulli process. Let's specify the following:

* Only one event at a time.

* Counts of events that happen in non-overlapping intervals are independent. 

## the Poisson process - II 

Then if we add a contant "rate" $\lambda$ per unit time of occurrences it turns out it *must* be that:

$$P(N(t) - N(s) = k) = \frac{[\lambda(t-s)]^k}{k!}e^{-\lambda(t-s)}.$$

We'll say $N(0) = 0$.

Many generalizations exist. The Poisson processes occupy a central role in probability. 

## practical examples (stolen from *Schay*)

Customers enter a store at a rate of 1 per minute. Find the probabilities that:

1. More than one will enter in the first minute.
2. More than two will enter in the first two minutes.
3. More than one will enter in each of the first two minutes.

Why and why not might a Poisson process model be suitable here?

